version: '3.9'
services: 

  nginx:
    image: matthewtee/dev_env_nginx:latest
    networks:
      - dev-environment-network
    ports:
      - "80:80"
    container_name: nginx-server
    restart: always
  
  dash_developer_app:
    image: matthewtee/dash_developer_portfolio:latest
    networks:
      - dev-environment-network
    environment:
      - PORT=8050
    container_name: dash_portfolio_site 
  
  zotero_dashboard:
    image: matthewtee/zotero-plotly-dashboard:latest
    networks: 
      - dev-environment-network
    environment:
      - PORT=8051
    container_name: zotero_dashboard
  
  rest_api:
    image: matthewtee/django_rest_api:latest
    networks: 
      - dev-environment-network
    env_file:
      - .env
    container_name: rest-api
    volumes: 
      - rest-api-db:/db.sqlite3

volumes:
  rest-api-db:

networks: 
  dev-environment-network:

