version: '3.9'
services: 

  nginx:
    image: matthewtee/dev_env_nginx:latest
    #build: ./nginx
    depends_on:
      - 'dash_developer_app'
      - 'zotero_dashboard'
      - 'flask-blog'
      - 'rest_api'
    networks:
      - dev-environment-network
    ports:
      - "80:80"
      - "81:81"

    container_name: nginx-server
    restart: always
  
  dash_developer_app:
    image: matthewtee/dash_developer_portfolio:latest
    networks:
      - dev-environment-network
    environment:
      - PORT=8050
    container_name: dash_portfolio_site 
  
  zotero_dashboard:
    image: matthewtee/zotero-plotly-dashboard:latest
    networks: 
      - dev-environment-network
    environment:
      - PORT=8051
    container_name: zotero_dashboard

  flask-blog:
    image: matthewtee/flask_blog_frotend:latest
    networks: 
      - dev-environment-network
    env_file:
      - flask.env
    container_name: flask-blog

  rest_api:
    image: matthewtee/django_rest_api:latest
    networks: 
      - dev-environment-network
    env_file:
      - .env
    container_name: rest-api

  rest-api-db:
    image: postgres:latest
    container_name: rest-api-db
    volumes: 
      - rest-api-db:/var/lib/postgresql/data
    env_file: 
      .env
    restart: always
    networks:
      - dev-environment-network


volumes:
  rest-api-db:

networks: 
  dev-environment-network:

